### ISSUE TITLE
How to ignore upper case uid string from ldap server ?

### ISSUE THREAD

**Issue by tjyang** [arthurdejong/nss-pam-ldapd#12]
We have ldap server storing uid as all upper case, in stead of lower case Unix uid.
nss-pam-ldapd-0.8.13-8 on centos 7 is failing due to this corrected behavior in this  newer version of nss-pam-ldapd. 

Currently this is our hack to avoid the the uid case check.

```
--- nslcd/pam.c.orig	2013-04-28 15:32:34.000000000 -0500
+++ nslcd/pam.c	2016-03-24 12:50:24.614661980 -0500
@@ -133,11 +133,13 @@
     return;
   }
   /* check if the username is different and update it if needed */
-  if (strcmp(username,value)!=0)
+  /* disable following 5 lines to ignore uid case checking */
+  /* if (strcmp(username,value)!=0)
   {
     log_log(LOG_INFO,"username changed from \"%s\" to \"%s\"",username,value);
     strcpy(username,value);
-  }
+   } 
+  */
 }

```

Will above hack causing security issue ?
Is there a better way to set the ignore case check from ldap server  in /etc/nslcd.conf instead ?

**Comment by tjyang** [comment]
This is another patch just  to ignore case comparison between username and value. 

```
--- nslcd/pam.c.orig    2013-04-28 16:32:34.000000000 -0400
+++ nslcd/pam.c 2016-03-25 03:07:54.432532891 -0400
@@ -133,7 +133,7 @@
     return;
   }
   /* check if the username is different and update it if needed */
-  if (strcmp(username,value)!=0)
+  if (strcasecmp(username,value)!=0)
   {
     log_log(LOG_INFO,"username changed from \"%s\" to \"%s\"",username,value);
     strcpy(username,value);

```

**Comment by tjyang** [comment]
Also I looked at nslcd.conf manpage, it has switch to ignore the case sensitive search, like following

```
  ignorecase yes|no
              This  specifies whether or not to perform searches for group, netgroup, passwd, protocols, rpc, services and shadow maps using
              case-insensitive matching.  Setting this to yes could open up the system to authorisation vulnerabilities and  introduce  nscd
              cache  poisoning  vulnerabilities  which  allow  denial of service.  The default is to perform case-sensitve filtering of LDAP
              search results for the above maps.
```

Why  there is no logic of using "if (strcasecmp(username,value)!=0)"  instead when "ignorecase yes" is set in /etc/nslcd.conf file ?

**Comment by arthurdejong** [comment]
Some applications don't support user and group names of different case as you would expect if you disable case checking. For instance, if you put a number of users in a local group that are restricted in some way, if a user logs in with a different case of their username, the access restrictions will not be applied.

If your LDAP server has users in uppercase and you want your Unix users to be all lowercase you either have to change the data in LDAP or use ignorecase.

**Comment by tjyang** [comment]
Thanks for the reply.
Changing the data in corporate LDAP server is close to impossible. 

I worked with Redhat support once and they also confirm "ignorecase yes" has no effect on ignoring case. 
This is confirmed by " if (strcmp(username,value)!=0)" line in nslcd/pam.c" since it is not using strcasecmp function.

Are you saying "ignorecase yes" setting in /etc/nslcd.conf should be able to ignore uppercase in my ldap server ?

**Comment by arthurdejong** [comment]
Specifying "ignorecase yes" should ignore the case if your LDAP server also works with case-insensitive usernames. This means that users FRED, fred and Fred all exist and point to the same user (have the same numeric uid). You can test this with "getent passwd Fred". One thing to not however is that if your LDAP server contains only uppercase usernames a listing of all users (getent passwd) will show the users in uppercase only.

If you do use "ignorecase yes" you should probably not be running nscd.

The code you quoted in nslcd/pam.c is meant to change the username to the cannonical form in LDAP. It could be that chaning that to STR_CMP() (which honors ignorecase) could help.

Something else to note is that pynslcd has an attribute mapping option to change values to lower case. However, pynslcd is still very much experimental and if you go that route I strongly recommend getting the latest 0.9.x version.

**Comment by tjyang** [comment]
On Fri, Mar 25, 2016 at 1:15 PM, Arthur de Jong <notifications@github.com>
wrote:

> Specifying "ignorecase yes" should ignore the case if your LDAP server
> also works with case-insensitive usernames. This means that users FRED,
> fred and Fred all exist and point to the same user (have the same numeric
> uid). You can test this with "getent passwd Fred". One thing to not however
> is that if your LDAP server contains only uppercase usernames a listing of
> all users (getent passwd) will show the users in uppercase only.
>

one a centos 7.2, I create create local lowercase uid in /etc/passwd and
only has password authentication going through ldap server while my ldap
server only store uppercase of uid.
This approach works on CentOS 5/6.x's nss-pam-slapd rpm.  It stopped
working starting from CentOS 7.x with newer version of nss-pam-slapd rpm.
Only "getent passwd fred" command will return fred uid entry, not Fred uid.

If you do use "ignorecase yes" you should probably not be running nscd.
>
I don't understanding this statement, will study it later.

> The code you quoted in nslcd/pam.c is meant to change the username to the
> cannonical form in LDAP. It could be that chaning that to STR_CMP() (which
> honors ignorecase) could help.
>
Is STR_CMP(), a typo ? , strmcmp() is case senstitve while stscasecmp() is
not.
See http://linux.die.net/man/3/strcasecmp

I am wondering why there is no such logic in pam.c update_username function

if ignorecase == yes
the use strcasecmp() to compare usename and value # case insensitive
comparison
else use strcmp() to compare usename and value       # case sensitive
comparison

> Something else to note is that pynslcd has an attribute mapping option to
> change values to lower case. However, pynslcd is still very much
> experimental and if you go that route I strongly recommend getting the
> latest 0.9.x version.
>

Thanks for this info, this is new to me.  I am hoping  come up with a patch
that can apply to centos7 src.rpm

> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/arthurdejong/nss-pam-ldapd/issues/12#issuecomment-201400459>
>



-- 
T.J. Yang

**Comment by shaimona** [comment]
I have ignorecase yes in nslcd.conf file. When trying to ssh I'm getting below error. Is there anything else I can do to get ssh working? using nss-pam-ldapd-0.8.13-8.el7.x86_64
Jun  1 21:45:56  sshd[2413]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=10.1xx.xx.xx  user=sathim
Jun  1 21:45:57 sshd[2413]: pam_ldap(sshd:auth): username changed from sathim to SATHIM
Jun  1 21:45:57 sshd[2413]: pam_unix(sshd:account): could not identify user (from getpwnam(SATHIM))
Jun  1 21:45:57 sshd[2413]: Failed password for sathim from 10.195.121.89 port 62987 ssh2
Jun  1 21:45:57 sshd[2413]: fatal: Access denied for user sathim by PAM account configuration [preauth]

**Comment by arthurdejong** [comment]
Are you sure you are not running nscd? Anyway I have pushed a89eda7 which should avoid changing the username if ignorecase is in effect.

**Comment by albert-a** [comment]
Could you tell me please, how "ignorecase yes" can affect security? It is mentioned in manual.

> For instance, if you put a number of users in a local group that are restricted in some way, if a user logs in with a different case of their username, the access restrictions will not be applied.

When I type `id uSEr` I still get correct set of groups on my system, as if I typed `id user`.
My LDAP server is Samba 4 AD, and it is case insensitive. Can there be any security vulnerabilities in this case?

It also mentioned that someone can poison the cache of nscd.. Could you also please explain what does it mean? And what consequences it may lead to.

**Comment by arthurdejong** [comment]
There are two issues related to the `ignorecase` option:

Some application can get confused if user or group names are used in some kind of ACL.
For example: Let's say that you don't want user "foo" to log in and in `sshd_config` you have `DenyUsers foo`. Most likely the user "Foo" can still log in. The same happens if you have a local (`/etc/group`) group "trainees" that has the user "foo". If the user "Foo" logs in they will not be in that group and their access may be handled differently. Any other application that does something with users (e.g. sudo, apache, mail server) could get confused in this way.

The other issue is that nscd (some implementations) can get confused because the forward cache and reverse caches seem to be linked.
For example, let's say you have a user "foo" with numeric uid of 2000. If you normally do `getent passwd 2000` you get the user "foo" returned. Once the user "Foo" logs in the same `getent passwd 2000` will now return a name of "Foo". That effectively means that any running processes will suddenly run under a different user name.
This can, especially combined with the above result in strange situations.
