### ISSUE TITLE
nslcd.py get_response asserts will be ignored when run in python optimization mode

### ISSUE THREAD

**Issue by ych** [arthurdejong/nss-pam-ldapd#14]
In get_response method of NslcdClient class, it uses assert to check response format [Here is the code](https://github.com/arthurdejong/nss-pam-ldapd/blob/master/utils/nslcd.py#L99)

But when programs run at python optimise mode(python -O), it will ignore asserts so the behavior of getent.py is not as execpted. Maybe you can use AssertionError or other exceptions to replace assert statements, thanks.

**Comment by arthurdejong** [comment]
Thanks for reporting this. I've replaced the assertions with raising exceptions. Fix is in a3da150.
