### ISSUE TITLE
nslcd.conf.5 typo fix: idle_timelimit entry "period if inactivity" -> "period of inactivity"

### ISSUE THREAD

**Issue by bsdbcr** [arthurdejong/nss-pam-ldapd#39]
Hi,
I found a typo in the man page for nslcd.conf.5.
In the idle_timelimit entry it says
"Specifies the period if inactivity (in seconds) after which the"
which should read:
"Specifies the period of inactivity (in seconds) after which the"

https://github.com/arthurdejong/nss-pam-ldapd/blob/548efe5333b56a0a042843a044e0348317f80065/man/nslcd.conf.5.xml#L517

**Comment by arthurdejong** [comment]
Hi Benedict, thanks for pointing this out (the typo was actually in there since 2007).
