### ISSUE TITLE
Compilation on Solaris

### ISSUE THREAD

**Issue by ckozler** [arthurdejong/nss-pam-ldapd#4]
Hey arthurdejong -

Thanks for providing nslcd and this entire package. It really is a great application and integrates well unlike most other similar tools

I am now trying to get this compiled on Solaris for company-wide standardization on authenticating against AD and I really need to use the ObjectSID auto-derive for UID since not everyone in the company has a uidNumber in AD. That said, I keep failing here and I suspect its a one-off Solaris type thing and I need to export something or use a different link flag

checking for minix/config.h... no
checking whether it is safe to define **EXTENSIONS**... yes
checking whether ln -s works... yes
checking for ar... no
checking for lib... no
checking for link... link -lib
checking the archiver (link -lib) interface... unknown
configure: error: could not determine link -lib interface

Can you assist? I tried picking apart the configure script as I have before but its tough to dive in to

**Comment by arthurdejong** [comment]
Closing issue because of no response. Feel free to re-open the issue or create a new one if it is still relevant.
