### ISSUE TITLE
Support not setting a base in nslcd.conf

### ISSUE THREAD

**Issue by eest** [arthurdejong/nss-pam-ldapd#50]
Hello,

In the LDAP directory I am using there are accounts (passwd entries) spread over multiple top-level bases in the tree. This makes it tricky to define a base. Currently we are just configuring multiple bases, one for each top-level directory, which of course leads to doing multiple lookups for each thing being looked up which is mostly just adding extra queries for no real gain.

I have not been able to figure out a way to define an "empty" base. Leaving it out is not possible, and setting it to `""` or `''` does not work either. Is there a way? Should there be a way?

**Comment by arthurdejong** [comment]
You might get away with searching on `cn=com` if all your search bases have that as part of their root but I'm not sure if the LDAP protocol supports that. If you find something that works with `ldapsearch` but doesn't with things you can specify in `nslcd.conf`, please let me know.

**Comment by arthurdejong** [comment]
@quanah thanks for the explanation. How is an empty base normally configured in ldap.conf? The manual page suggests to not use double quotes so this seems invalid:

    base ""

this also seems weird (no idea if this is valid at all):

    base

Is having an empty base a reasonable default value (nslcd now falls back to getting the naming context form the rootDSE)?

**Comment by arthurdejong** [comment]
Hmm, with `ldap_search_ext(ld, "", LDAP_SCOPE_SUBTREE, "(&(objectClass=posixAccount)(uid=arthur))",...)` I get "No such object". Using `NULL` as base instead of `""` has the same result. This is with Debian's OpenLDAP client library 2.4.59 and slapd 2.4.47 on the server.

**Comment by quanah** [comment]
It's not necessary to do the above if the server is configured to serve from the empty base (i.e., the database has suffix "").  That's an uncommon configuration.  However, the empty base is always present, but provides minimal information, and you have to scope the search appropriately, i.e.:

ldapsearch ... -s base -b ""

when the suffix of the database is something other than "" (like dc=example,dc=com or whatever).
