### ISSUE TITLE
Needs to use closefrom on FreeBSD

### ISSUE THREAD

**Issue by asomers** [arthurdejong/nss-pam-ldapd#53]
`exec_invalidate` in nslcd/invalidator.c tries to close every open file descriptor.  It does that by starting with `sysconf(_SC_OPEN_MAX) - 1` and iterating downwards toward 0, calling `close` on each one.  But on FreeBSD, `_SC_OPEN_MAX` autoscales with available RAM and can easily reach into the millions.  So starting `nslcd` can take more than a minute.
The best solution is probably to use `closefrom`.  Available since FreeBSD 8.0, it can close all file descriptors quickly, with a single syscall.
https://github.com/arthurdejong/nss-pam-ldapd/blob/2fc652fa11b03fc5aafe353a790c103f49540831/nslcd/invalidator.c#L100
https://www.freebsd.org/cgi/man.cgi?query=closefrom&sektion=2&format=html

**Comment by arthurdejong** [comment]
Hi @asomers,

Thanks for pointing this out. I've pushed a fix as 2f6e65a.

**Comment by asomers** [comment]
Thanks!  That was really fast.
