### ISSUE TITLE
nss-pam-ldap test case error

### ISSUE THREAD

**Issue by navinagaraj** [arthurdejong/nss-pam-ldapd#56]
Hi,

   I am trying the latest version 0.9.12, and while testing I am facing those errors. attache a log for your reference.

ERROR CASES:
                          1. test_myldap.sh [test_myldap.log](https://github.com/arthurdejong/nss-pam-ldapd/files/9936158/test_myldap.log)
                          2. test_nsscmds.sh [test_nsscmds.log](https://github.com/arthurdejong/nss-pam-ldapd/files/9936157/test_nsscmds.log)
                          3. test_ldapcmds.sh [test_ldapcmds.log](https://github.com/arthurdejong/nss-pam-ldapd/files/9936155/test_ldapcmds.log)

**Comment by arthurdejong** [comment]
Hi @navinagaraj,

Sorry for not replying sooner. Most of the tests that require an LDAP server expect the LDAP server to have a particular content (tests/test.ldif). The NSS and PAM tests also depend on the system being configured in a certain way (see tests/README).

The tests are probably a little fragile to be run from an arbitrary system on the command line. I should probably add an easy way to run the tests via Docker (Github actions also run the tests).

**Comment by navinagaraj** [comment]
ok Thanks @arthurdejong .
