### ISSUE TITLE
Possible dereference of NULL

### ISSUE THREAD

**Issue by VoroninArtemii** [arthurdejong/nss-pam-ldapd#70]
There is a possible derefernce of NULL here:
https://github.com/arthurdejong/nss-pam-ldapd/blob/b7841fc5647fafcea9258e13190ee2058dd4e7b0/nslcd/passwd.c#L328
The pointer `dn2uid` is checked here and we don't do anything after this block if the memory has not been allocated:
https://github.com/arthurdejong/nss-pam-ldapd/blob/b7841fc5647fafcea9258e13190ee2058dd4e7b0/nslcd/passwd.c#L295-L297

Found by Linux Verification Center ([portal.linuxtesting.ru](http://portal.linuxtesting.ru/)) with SVACE.
Author A. Voronin.

**Comment by arthurdejong** [comment]
Thanks for pointing this out. It has been fixed in 91bb8c9. It should only be possible to trigger this if a call to `malloc()` failed.
