### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by VoroninArtemii** [arthurdejong/nss-pam-ldapd#71]
There is a possible memory leak:
https://github.com/arthurdejong/nss-pam-ldapd/blob/b7841fc5647fafcea9258e13190ee2058dd4e7b0/nslcd/cfg.c#L687-L688
We allocate memory here and then just lose the pointer:
https://github.com/arthurdejong/nss-pam-ldapd/blob/b7841fc5647fafcea9258e13190ee2058dd4e7b0/nslcd/cfg.c#L670

Found by Linux Verification Center ([portal.linuxtesting.ru](http://portal.linuxtesting.ru/)) with SVACE.
Author A. Voronin.

**Comment by arthurdejong** [comment]
Thanks for pointing this out. It has been fixed in 9a353ac. I think I saw this earlier in valgrind but never took the effort to track this down since this is a one-time leak of a few bytes of memory.
