### ISSUE TITLE
pam_authz doesn't seem search in all the bases

### ISSUE THREAD

**Issue by kadogo** [arthurdejong/nss-pam-ldapd#9]
Hi,
I use nslcd with multiple base but my pam_authz search only in the first base.

base ou=people,dc=base,dc=be
base ou=groups,dc=base,dc=be
base ou=people,ou=branch,dc=base,dc=be
base ou=groups,ou=branch,dc=base,dc=be
base ou=people,dc=base,dc=be
base ou=groups,dc=base,dc=be

pam_authz_search (&(objectClass=posixAccount)(uid=$username)(|(host=$hostname)(host=$fqdn)(host=\\*)))

To bypass the issue I use now this
base dc=opensides,dc=be

**Comment by arthurdejong** [comment]
Which version of nss-pam-ldapd are you using?

Version 0.9.0 introduced searching across several search bases.

**Comment by kadogo** [comment]
I was in classical wheezy version 0.8.x, I just try the backport for 0.9.x and it work nice (after a purge of nslcd, libpam-ldapd and libnss-ldapd).

Sorry for disturbing and thanks.
